# Generated by Django 3.2.7 on 2023-04-10 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0005_leave'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.class')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.teacher')),
            ],
        ),
    ]
