# Generated by Django 3.2.7 on 2023-04-11 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0007_attendance_attendance_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leave',
        ),
    ]
