# Generated by Django 3.2.7 on 2023-04-13 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0010_auto_20230413_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classs',
        ),
        migrations.RemoveField(
            model_name='student',
            name='section',
        ),
        migrations.RemoveField(
            model_name='student',
            name='session_year',
        ),
    ]
