# Generated by Django 3.2.7 on 2023-04-13 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0012_auto_20230413_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance_report',
            name='attendance',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
