# Generated by Django 3.2.7 on 2023-04-13 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0013_auto_20230413_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('is_present', models.BooleanField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clas', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schoolapp.class')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schoolapp.section')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schoolapp.session_year')),
            ],
        ),
    ]
