# Generated by Django 3.2.7 on 2023-04-13 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0014_attendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance_Report',
        ),
    ]
