# Generated by Django 3.2.7 on 2023-04-17 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0016_attendance_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher_Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No_of_days', models.CharField(max_length=100, null=True)),
                ('leave_type', models.CharField(max_length=100, null=True)),
                ('details', models.CharField(max_length=100, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schoolapp.teacher')),
            ],
        ),
        migrations.DeleteModel(
            name='Leave',
        ),
    ]
